apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-opex-analytics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-opex-analytics.labels" . | nindent 4 }}
---
{{ if .Values.useRoleBinding }}
apiVersion:  rbac.authorization.k8s.io/v1beta1
{{ else }}
apiVersion: rbac.authorization.k8s.io/v1
{{ end }}
{{ if .Values.useRoleBinding }}
kind: Role
{{ else }}
kind: ClusterRole
{{ end }}
metadata:
  name: {{ include "kube-opex-analytics.fullname" . }}
  labels:
    {{- include "kube-opex-analytics.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - nodes/stats
  - pods
  verbs:
  - get
  - list
  - watch
---
{{ if .Values.useRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{ else }}
apiVersion: rbac.authorization.k8s.io/v1
{{ end }}
{{ if .Values.useRoleBinding }}
kind: RoleBinding
{{ else }}
kind: ClusterRoleBinding
{{ end }}
metadata:
  name: {{ include "kube-opex-analytics.fullname" . }}
  labels:
    {{- include "kube-opex-analytics.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{ if .Values.useRoleBinding }}
  kind: Role
{{ else }}
  kind: ClusterRole
{{ end }}
  name: {{ include "kube-opex-analytics.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-opex-analytics.fullname" . }}
  namespace: {{ .Release.Namespace }}
